# Generated by Django 5.1.2 on 2024-10-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='anio',
            new_name='año',
        ),
    ]
