# Generated by Django 5.1.2 on 2024-10-11 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id_estacionamiento', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('capacidad_total', models.IntegerField()),
                ('espacios_disponibles', models.IntegerField()),
                ('tarifa_hora', models.IntegerField()),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id_espacio', models.AutoField(primary_key=True, serialize=False)),
                ('numero_espacio', models.CharField(max_length=10)),
                ('piso', models.IntegerField()),
                ('tipo_espacio', models.CharField(max_length=100)),
                ('ocupado', models.BooleanField(default=False)),
                ('sensor_id', models.IntegerField()),
                ('id_estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.estacionamiento')),
            ],
        ),
    ]
