# Generated by Django 5.1.2 on 2024-10-11 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacionamientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('hora_entrada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('estado_reserva', models.CharField(max_length=100)),
                ('espacio_reservado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.espacio')),
                ('id_estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.estacionamiento')),
            ],
        ),
    ]
